# item
_teknoo_website_admin_item_list:
    path: '/items'
    methods:  ['GET', 'POST']
    defaults:
        _controller: 'teknoo.east.common.endpoint.crud.list'
        defaultOrderDirection: 'ASC'
        errorTemplate: '@@TeknooEastCommon/Error/<error>.html.twig'
        itemsPerPage: 20
        loader: '@Teknoo\East\Website\Loader\ItemLoader'
        template: '@@TeknooEastWebsite/AdminItem/list.html.twig'
        cleanHtml: "%teknoo.east.website.admin.rendering.clean_html%"

_teknoo_website_admin_item_edit:
    path: '/item/edit/{id}'
    methods:  ['GET', 'POST', 'PUT']
    defaults:
        _controller: 'teknoo.east.common.endpoint.crud.edit'
        errorTemplate: '@@TeknooEastCommon/Error/<error>.html.twig'
        formClass: 'Teknoo\East\Website\Doctrine\Form\Type\ItemType'
        formOptions: { "doctrine_type": "%teknoo.east.common.form_type.doctrine.class%"}
        isTranslatable: true
        loader: '@Teknoo\East\Website\Loader\ItemLoader'
        slugField: 'slug'
        template: '@@TeknooEastWebsite/AdminItem/edit.html.twig'
        writer: '@Teknoo\East\Website\Writer\ItemWriter'
        cleanHtml: "%teknoo.east.website.admin.rendering.clean_html%"

_teknoo_website_admin_item_new:
    path: '/item/new'
    methods:  ['GET', 'POST', 'PUT']
    defaults:
        _controller: 'teknoo.east.common.endpoint.crud.new'
        errorTemplate: '@@TeknooEastCommon/Error/<error>.html.twig'
        formClass: 'Teknoo\East\Website\Doctrine\Form\Type\ItemType'
        formOptions: { "doctrine_type": "%teknoo.east.common.form_type.doctrine.class%"}
        isTranslatable: true
        loader: '@Teknoo\East\Website\Loader\ItemLoader'
        objectClass: 'Teknoo\East\Website\Doctrine\Object\Item'
        route: '_teknoo_website_admin_item_edit'
        slugField: 'slug'
        template: '@@TeknooEastWebsite/AdminItem/new.html.twig'
        writer: '@Teknoo\East\Website\Writer\ItemWriter'
        cleanHtml: "%teknoo.east.website.admin.rendering.clean_html%"

_teknoo_website_admin_item_delete:
    path: '/item/delete/{id}'
    methods:  ['GET', 'DELETE']
    defaults:
        _controller: 'teknoo.east.common.endpoint.crud.delete'
        deleter: '@teknoo.east.website.deleting.item'
        errorTemplate: '@@TeknooEastCommon/Error/<error>.html.twig'
        loader: '@Teknoo\East\Website\Loader\ItemLoader'
        route: '_teknoo_website_admin_item_list'

# content
_teknoo_website_admin_content_list:
    path: '/contents'
    methods:  ['GET', 'POST']
    defaults:
        _controller: 'teknoo.east.common.endpoint.crud.list'
        defaultOrderDirection: 'ASC'
        errorTemplate: '@@TeknooEastCommon/Error/<error>.html.twig'
        itemsPerPage: 20
        loader: '@Teknoo\East\Website\Loader\ContentLoader'
        template: '@@TeknooEastWebsite/AdminContent/list.html.twig'
        cleanHtml: "%teknoo.east.website.admin.rendering.clean_html%"

_teknoo_website_admin_content_edit:
    path: '/content/edit/{id}'
    methods:  ['GET', 'POST', 'PUT']
    defaults:
        _controller: 'teknoo.east.common.endpoint.crud.edit'
        errorTemplate: '@@TeknooEastCommon/Error/<error>.html.twig'
        formClass: 'Teknoo\East\Website\Doctrine\Form\Type\ContentType'
        formOptions: { "doctrine_type": "%teknoo.east.common.form_type.doctrine.class%"}
        isTranslatable: true
        loader: '@Teknoo\East\Website\Loader\ContentLoader'
        slugField: 'slug'
        template: '@@TeknooEastWebsite/AdminContent/edit.html.twig'
        writer: '@Teknoo\East\Website\Writer\ContentWriter'
        cleanHtml: "%teknoo.east.website.admin.rendering.clean_html%"

_teknoo_website_admin_content_new:
    path: '/content/new'
    methods:  ['GET', 'POST', 'PUT']
    defaults:
        _controller: 'teknoo.east.common.endpoint.crud.new'
        errorTemplate: '@@TeknooEastCommon/Error/<error>.html.twig'
        formClass: 'Teknoo\East\Website\Doctrine\Form\Type\ContentType'
        formOptions: { "doctrine_type": "%teknoo.east.common.form_type.doctrine.class%"}
        isTranslatable: true
        loader: '@Teknoo\East\Website\Loader\ContentLoader'
        objectClass: 'Teknoo\East\Website\Doctrine\Object\Content'
        route: '_teknoo_website_admin_content_edit'
        slugField: 'slug'
        template: '@@TeknooEastWebsite/AdminContent/new.html.twig'
        writer: '@Teknoo\East\Website\Writer\ContentWriter'
        cleanHtml: "%teknoo.east.website.admin.rendering.clean_html%"

_teknoo_website_admin_content_delete:
    path: '/content/delete/{id}'
    methods:  ['GET', 'DELETE']
    defaults:
        _controller: 'teknoo.east.common.endpoint.crud.delete'
        deleter: '@teknoo.east.website.deleting.content'
        errorTemplate: '@@TeknooEastCommon/Error/<error>.html.twig'
        loader: '@Teknoo\East\Website\Loader\ContentLoader'
        route: '_teknoo_website_admin_content_list'

# media
_teknoo_website_admin_media_list:
    path: '/media'
    methods:  ['GET', 'POST']
    defaults:
        _controller: 'teknoo.east.common.endpoint.crud.list'
        defaultOrderDirection: 'ASC'
        errorTemplate: '@@TeknooEastCommon/Error/<error>.html.twig'
        itemsPerPage: 20
        loader: '@Teknoo\East\Common\Loader\MediaLoader'
        template: '@@TeknooEastCommon/AdminMedia/list.html.twig'
        cleanHtml: "%teknoo.east.website.admin.rendering.clean_html%"

_teknoo_website_admin_media_new:
    path: '/media/new'
    methods:  ['GET', 'POST', 'PUT']
    defaults:
        _controller: 'teknoo.east.common.endpoint.crud.new'
        errorTemplate: '@@TeknooEastCommon/Error/<error>.html.twig'
        formClass: 'Teknoo\East\CommonBundle\Form\Type\MediaType'
        formOptions: { }
        loader: '@Teknoo\East\Common\Loader\MediaLoader'
        objectClass: 'Teknoo\East\Common\Doctrine\Object\Media'
        route: '_teknoo_common_admin_media_list'
        template: '@@TeknooEastCommon/AdminMedia/new.html.twig'
        writer: '@Teknoo\East\Common\Doctrine\Writer\ODM\MediaWriter'
        cleanHtml: "%teknoo.east.website.admin.rendering.clean_html%"

_teknoo_website_admin_media_delete:
    path: '/media/delete/{id}'
    methods:  ['GET', 'DELETE']
    defaults:
        _controller: 'teknoo.east.common.endpoint.crud.delete'
        deleter: '@teknoo.east.common.deleting.media'
        errorTemplate: '@@TeknooEastCommon/Error/<error>.html.twig'
        loader: '@Teknoo\East\Common\Loader\MediaLoader'
        route: '_teknoo_common_admin_media_list'

# type
_teknoo_website_admin_type_list:
    path: '/types'
    methods:  ['GET', 'POST']
    defaults:
        _controller: 'teknoo.east.common.endpoint.crud.list'
        defaultOrderDirection: 'ASC'
        errorTemplate: '@@TeknooEastCommon/Error/<error>.html.twig'
        itemsPerPage: 20
        loader: '@Teknoo\East\Website\Loader\TypeLoader'
        template: '@@TeknooEastWebsite/AdminType/list.html.twig'
        cleanHtml: "%teknoo.east.website.admin.rendering.clean_html%"

_teknoo_website_admin_type_edit:
    path: '/type/edit/{id}'
    methods:  ['GET', 'POST', 'PUT']
    defaults:
        _controller: 'teknoo.east.common.endpoint.crud.edit'
        errorTemplate: '@@TeknooEastCommon/Error/<error>.html.twig'
        formClass: 'Teknoo\East\WebsiteBundle\Form\Type\TypeType'
        formOptions: { }
        loader: '@Teknoo\East\Website\Loader\TypeLoader'
        template: '@@TeknooEastWebsite/AdminType/edit.html.twig'
        writer: '@Teknoo\East\Website\Writer\TypeWriter'
        cleanHtml: "%teknoo.east.website.admin.rendering.clean_html%"

_teknoo_website_admin_type_new:
    path: '/type/new'
    methods:  ['GET', 'POST', 'PUT']
    defaults:
        _controller: 'teknoo.east.common.endpoint.crud.new'
        errorTemplate: '@@TeknooEastCommon/Error/<error>.html.twig'
        formClass: 'Teknoo\East\WebsiteBundle\Form\Type\TypeType'
        formOptions: { }
        loader: '@Teknoo\East\Website\Loader\TypeLoader'
        objectClass: 'Teknoo\East\Website\Object\Type'
        route: '_teknoo_website_admin_type_edit'
        template: '@@TeknooEastWebsite/AdminType/new.html.twig'
        writer: '@Teknoo\East\Website\Writer\TypeWriter'
        cleanHtml: "%teknoo.east.website.admin.rendering.clean_html%"

_teknoo_website_admin_type_delete:
    path: '/type/delete/{id}'
    methods:  ['GET', 'DELETE']
    defaults:
        _controller: 'teknoo.east.common.endpoint.crud.delete'
        deleter: '@teknoo.east.website.deleting.type'
        errorTemplate: '@@TeknooEastCommon/Error/<error>.html.twig'
        loader: '@Teknoo\East\Website\Loader\TypeLoader'
        route: '_teknoo_website_admin_type_list'

# user
_teknoo_website_admin_user_list:
    path: '/users'
    methods:  ['GET', 'POST']
    defaults:
        _controller: 'teknoo.east.common.endpoint.crud.list'
        defaultOrderDirection: 'ASC'
        errorTemplate: '@@TeknooEastCommon/Error/<error>.html.twig'
        itemsPerPage: 20
        loader: '@Teknoo\East\Common\Loader\UserLoader'
        template: '@@TeknooEastWebsite/AdminUser/list.html.twig'
        cleanHtml: "%teknoo.east.website.admin.rendering.clean_html%"

_teknoo_website_admin_user_edit:
    path: '/user/edit/{id}'
    methods:  ['GET', 'POST', 'PUT']
    defaults:
        _controller: 'teknoo.east.common.endpoint.crud.edit'
        errorTemplate: '@@TeknooEastCommon/Error/<error>.html.twig'
        formClass: 'Teknoo\East\CommonBundle\Form\Type\UserType'
        formOptions: {}
        loader: '@Teknoo\East\Common\Loader\UserLoader'
        template: '@@TeknooEastWebsite/AdminUser/edit.html.twig'
        writer: '@Teknoo\East\CommonBundle\Writer\SymfonyUserWriter'
        cleanHtml: "%teknoo.east.website.admin.rendering.clean_html%"

_teknoo_website_admin_user_new:
    path: '/user/new'
    methods:  ['GET', 'POST', 'PUT']
    defaults:
        _controller: 'teknoo.east.common.endpoint.crud.new'
        errorTemplate: '@@TeknooEastCommon/Error/<error>.html.twig'
        formClass: 'Teknoo\East\CommonBundle\Form\Type\UserType'
        formOptions: {}
        loader: '@Teknoo\East\Common\Loader\UserLoader'
        objectClass: 'Teknoo\East\Common\Object\User'
        route: '_teknoo_website_admin_user_edit'
        template: '@@TeknooEastWebsite/AdminUser/new.html.twig'
        writer: '@Teknoo\East\CommonBundle\Writer\SymfonyUserWriter'
        cleanHtml: "%teknoo.east.website.admin.rendering.clean_html%"

_teknoo_website_admin_user_delete:
    path: '/user/delete/{id}'
    methods:  ['GET', 'DELETE']
    defaults:
        _controller: 'teknoo.east.common.endpoint.crud.delete'
        deleter: '@teknoo.east.common.deleting.user'
        errorTemplate: '@@TeknooEastCommon/Error/<error>.html.twig'
        loader: '@Teknoo\East\Common\Loader\UserLoader'
        route: '_teknoo_website_admin_user_list'
