_teknoo_website_post_comment:
    path: '/post/{slug}/comment'
    methods:  ['POST', 'PUT']
    defaults:
        _controller: 'teknoo.east.website.endpoint.post.comment'
        errorTemplate: '@@TeknooEastCommon/Error/<error>.html.twig'
        cleanHtml: "%teknoo.east.website.rendering.clean_html%"
        objectClass: '%teknoo.east.website.dto.comment.class%'
        formClass: 'Teknoo\East\WebsiteBundle\Form\Type\NewCommentType'
        formOptions:
            comment_class: '%teknoo.east.website.persisted.comment.class%'
        route: '_teknoo_website_post'
        writer: '@Teknoo\East\Website\Writer\CommentWriter'
    requirements:
        slug: ((?!_wdt|_profiler).).+
