_teknoo_website_media:
    path: '/media/{id}'
    methods:  ['GET']
    defaults:
        _controller: 'teknoo.east.common.endpoint.media'
        errorTemplate: '@@TeknooEastCommon/Error/<error>.html.twig'

_teknoo_website_content:
    path: '/{slug}'
    methods:  ['GET']
    defaults:
        _controller: 'teknoo.east.website.endpoint.content'
        errorTemplate: '@@TeknooEastCommon/Error/<error>.html.twig'
    requirements:
        slug: ((?!_wdt|_profiler).).+

_teknoo_website_home:
    path: '/'
    methods:  ['GET']
    defaults:
        _controller: 'teknoo.east.website.endpoint.content'
        errorTemplate: '@@TeknooEastCommon/Error/<error>.html.twig'
        slug: '/'
