parameters:
    #Bowls
    teknoo.east.website.endpoint.content.bowl.class: 'Teknoo\Recipe\Bowl\FiberRecipeBowl'
    teknoo.east.website.endpoint.media.bowl.class: 'Teknoo\Recipe\Bowl\FiberRecipeBowl'

    teknoo.east.website.admin.rendering.clean_html: true
    teknoo.east.website.rendering.clean_html: false

    teknoo.east.website.sanitize.default_context: ~
    teknoo.east.website.sanitize.salt: '%env(TEKNOO_EAST_WEBSITE_SANITIZE_SALT)%'
    env(TEKNOO_EAST_WEBSITE_SANITIZE_SALT): youmustchangeit

services:
    #Generic endpoints
    teknoo.east.website.endpoint.content.bowl:
        class: '%teknoo.east.website.endpoint.content.bowl.class%'
        arguments:
            - '@Teknoo\East\Website\Contracts\Recipe\Cookbook\RenderDynamicContentEndPointInterface'
            - 0

    teknoo.east.website.endpoint.content:
        class: 'Teknoo\East\Foundation\EndPoint\RecipeEndPoint'
        public: true
        arguments:
            - '@teknoo.east.website.endpoint.content.bowl'
            - '@service_container'

    teknoo.east.website.endpoint.media.bowl:
        class: '%teknoo.east.website.endpoint.media.bowl.class%'
        arguments:
            - '@Teknoo\East\Common\Contracts\Recipe\Cookbook\RenderMediaEndPointInterface'
            - 0

    teknoo.east.website.endpoint.media:
        class: 'Teknoo\East\Foundation\EndPoint\RecipeEndPoint'
        public: true
        arguments:
            - '@teknoo.east.website.endpoint.media.bowl'
            - '@service_container'

    Teknoo\East\Website\Twig\Extension\SanitizedContent:
        arguments:
            - '@?Symfony\Component\HtmlSanitizer\HtmlSanitizerInterface'
        tags:
            - { name: "twig.extension" }

    Teknoo\East\Website\Doctrine\Form\Type\ContentType:
        class: 'Teknoo\East\Website\Doctrine\Form\Type\ContentType'
        arguments:
            - '@?Symfony\Component\HtmlSanitizer\HtmlSanitizerInterface'
            - '%teknoo.east.website.sanitize.default_context%'
            - '%teknoo.east.website.sanitize.salt%'
        tags:
            - {name: form.type}