parameters:
    #Bowls
    teknoo.east.website.endpoint.content.bowl.class: 'Teknoo\Recipe\Bowl\FiberRecipeBowl'
    teknoo.east.website.endpoint.media.bowl.class: 'Teknoo\Recipe\Bowl\FiberRecipeBowl'

services:
    #Generic endpoints
    teknoo.east.website.endpoint.content.bowl:
        class: '%teknoo.east.website.endpoint.content.bowl.class%'
        arguments:
            - '@Teknoo\East\Website\Contracts\Recipe\Cookbook\RenderDynamicContentEndPointInterface'
            - 0

    teknoo.east.website.endpoint.content:
        class: 'Teknoo\East\Foundation\EndPoint\RecipeEndPoint'
        public: true
        arguments:
            - '@teknoo.east.website.endpoint.content.bowl'
            - '@service_container'

    teknoo.east.website.endpoint.media.bowl:
        class: '%teknoo.east.website.endpoint.media.bowl.class%'
        arguments:
            - '@Teknoo\East\Website\Contracts\Recipe\Cookbook\RenderMediaEndPointInterface'
            - 0

    teknoo.east.website.endpoint.media:
        class: 'Teknoo\East\Foundation\EndPoint\RecipeEndPoint'
        public: true
        arguments:
            - '@teknoo.east.website.endpoint.media.bowl'
            - '@service_container'
